### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by koo0ki** [titsex/distube-vk-music-plugin#1]
DisTubeError [YTDLP_ERROR]: Error: ERROR: Unsupported URL: https://vk.com/badbrowser.php
null

    at /home/koo0ki/work/Новые боты/Music/node_modules/@distube/yt-dlp/dist/index.js:152:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async YtDlpPlugin.resolve (/home/koo0ki/work/Новые боты/Music/node_modules/@distube/yt-dlp/dist/index.js:144:18)
    at async _DisTube.play (/home/koo0ki/work/Новые боты/Music/node_modules/distube/dist/index.js:2297:24) {
  errorCode: 'YTDLP_ERROR'
} Promise {
  <rejected> DisTubeError [YTDLP_ERROR]: Error: ERROR: Unsupported URL: https://vk.com/badbrowser.php
  null
  
      at /home/koo0ki/work/Новые боты/Music/node_modules/@distube/yt-dlp/dist/index.js:152:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async YtDlpPlugin.resolve (/home/koo0ki/work/Новые боты/Music/node_modules/@distube/yt-dlp/dist/index.js:144:18)
      at async _DisTube.play (/home/koo0ki/work/Новые боты/Music/node_modules/distube/dist/index.js:2297:24) {
    errorCode: 'YTDLP_ERROR'
  }
}

**Comment by titsex** [comment]
Hello.

https://vk.com/badbrowser.php the URL is not supported.

Look at this readme.md:
![image](https://github.com/user-attachments/assets/80190ef7-63bd-4f27-9f31-fbba21d45dd4 )

PS: the plugin does not work for the v5 distube (temporarily)
